### ISSUE TITLE
Threading CPU Contention

### ISSUE THREAD

**Issue by acedrew** [ut-cuip/utc-cuip-video-event-producer#8]
Currently, it appears that all of the streamers are in threads owned by the frame processor, while this is great for the network I/O, allowing it to happen without blocking execution, CPU bound tasks like jpeg encoding and frame resizing are tying up the frame processor GIL.

I would recommend refactoring the streaming out to a single process, managed by the initial run process, rather than inside the frame processor and that can serve all stream routes dynamically, similar to the example here: https://github.com/ut-cuip/quart-opencv-streamer
It would receive (camera-id, frame) pairs on a queue, generating the JPEG frame on ingest. Then it would serve the same frame to each client until receiving an update. In the example, I've used another set of queues to ensure that each client is only sent a specific frame once. This could be easily replaced by a Semaphore, for possible lighter weight in memory and CPU.

**Comment by oitsjustjose** [comment]
Closed with 0a3227981f4a125ebb58cb79d1b066f5c25d8c0f
